version: '3.2'
services:
  check_poco:
    tty: true
    container_name: user_service
    build:
      dockerfile: Dockerfile
    volumes:
      - './src:/src/'
    ports:
      - 8080:8080
    entrypoint:
    # ["cat", "main.cpp"]
      ["/bin/bash", "/src/start_work.sh"]
      # ["ls"]
      # ["cat", "test.txt"]
    networks:
      - network

networks:
  network:
    driver: "bridge"
    external: false
